language: c
compiler: gcc
python:   "2.7"

install:
    - sudo pip install --only-binary=numpy,scipy numpy scipy

before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/python

script:
    - make
    - make test
    - make pytest

notifications:
    email: false
